version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: nht_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  api:
    image: ghcr.io/toannguyen3105/nht-bsihuyen.com-api:main
    container_name: nht_api
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      # HTTP Router (Redirect to HTTPS)
      - "traefik.http.routers.nht-api-http.rule=Host(`api.bshuyen.io.vn`)"
      - "traefik.http.routers.nht-api-http.entrypoints=web"
      - "traefik.http.routers.nht-api-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # HTTPS Router
      - "traefik.http.routers.nht-api.rule=Host(`api.bshuyen.io.vn`)"
      - "traefik.http.routers.nht-api.entrypoints=websecure"
      - "traefik.http.routers.nht-api.tls.certresolver=myresolver"
    networks:
      - default
      - web_network

volumes:
  postgres_data:

networks:
  web_network:
    external: true
